### PR TITLE
Lighthouse integration to CI (minimum score & budget)

### PR DESCRIPTION
**Pull request by thomasmarcelin**
**Lighthouse integration to CI.**

- Minimum score requirements can be found in package.json , they can be configured manually.
- Budget can be found in ci-scripts/budget.json, as per Google documentation (default value are from here : https://developers.google.com/web/tools/lighthouse/audits/budgets)
- This adds a last step in circle ci, after deployment. It won't cancel/revert deployment if the audit doesn't pass.
- Unfortunately, Google doesn't have an official Docker image for lighthouse + node, so I found another one on docker hub

### CODE REVIEW

**Comment by kefranabg** [comment]
Thanks @thomasmarcelin for this PR ! We'll take a look ASAP

**Comment by thomasmarcelin** [comment]
Whoops, prettier failed, i'll amend that

**Comment by kefranabg** [comment]
Hi @thomasmarcelin,

First, thank you for your work 🙏 

From what I've seen in your PR, the lighthouse check is based on the project that is already in production.

What is expected is that the budget check run before the deployment, on the builded app from the pull request, not on the app that is already in production.

The idea is to let the pull request pass the CI only if its lighthouse score is ok.

I'll close this PR for now, but please feel free to open a new one if you want to fix the workflow 😉

**Comment by thomasmarcelin** [comment]
Lighthouse requires an URL to work, so I guess I need to run a webserver for this to work after the build? 

But since there's a deployment step in circle ci, why bother running an extra webserver when firebase hosting can provide one? It can be whatever link you want, there is a test url variable in circleci.yml
If you setup a staging area where PR are deployed it should be fine!

**Pull request closed without merging**
