### PR TITLE
:wrench: Add source and update max-age value for hosting Headers

### PR DESCRIPTION
**Pull request by VincentBourdeau**
### Web Perf and optimizations bests practices. 
Boosting performances score and helping load time by adding Styles (css) and Scripts (js) to the hosting headers and changing the max-age value.

### CODE REVIEW

**Comment by kefranabg** [comment]
Hey, thanks for opening this PR.

Are you sure that it's working well with service worker update process? Like when a new version of the app is available ?

**Comment by VincentBourdeau** [comment]
> Are you sure that it's working well with service worker update process? Like when a new version of the app is available ?

Hey :) - It will of course cache any CSS + Js files but the New Content Available Toastr will still show up and work properly. Upon 'clicking' the REFRESH link, (and only then) the user will be able to see the new styles and content.

**Comment by kefranabg** [comment]
@all-contributors add @VincentBourdeau for code

**Comment by kefranabg** [comment]
Feel free to submit a new PR to update the contributors list !

**Pull request merged**
